apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.service.name | default (printf "%s-svc" (include "fullname" .))}}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.socketio.port }}
    targetPort: {{ .Values.socketio.port }}
    protocol: TCP
    name: ws
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
