management:
  security:
    enabled: false
  server:
    base-path: /
    port: 8081
    servlet:
      context-path: /
  endpoints:
    web:
      base-path: /ontimize
spring:
  flyway:
    enabled: false
environment:
  url: https://cd2024bfs3g1-dev.dev.campusdual.com/